name: Create Release

on:
  push:
    branches:
      - "main"

env:
  NODE_VERSION: "20.x"

jobs:
  get-protection-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Generator token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_RELEASE_APP_ID }}
          private_key: ${{ secrets.GH_RELEASE_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Get Branch Protection Rules
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ananda11k/test-update-branch-prot-rules/branches/main/protection
      - name: Update Branch Protection Rules
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ananda11k/test-update-branch-prot-rules/branches/main/protection \
            -F "required_status_checks[strict]=true" -f "required_status_checks[contexts[]]=continuous-integration/travis-ci" -F "enforce_admins=true" -f "dismissal_restrictions[users[]]=octocat" -f "dismissal_restrictions[teams[]]=justice-league" -F "required_pull_request_reviews[dismiss_stale_reviews]=true" -F "required_pull_request_reviews[require_code_owner_reviews]=true" -F "required_pull_request_reviews[required_approving_review_count]=2" -F "required_pull_request_reviews[require_last_push_approval]=true" -f "bypass_pull_request_allowances[users[]]=octocat" -f "bypass_pull_request_allowances[teams[]]=justice-league" -f "restrictions[users[]]=octocat" -f "restrictions[teams[]]=justice-league" -f "restrictions[apps[]]=super-ci" -F "required_linear_history=true" -F "allow_force_pushes=true" -F "allow_deletions=true" -F "block_creations=true" -F "required_conversation_resolution=true" -F "lock_branch=true" -F "allow_fork_syncing=true"
