name: Create Release

on:
  push:
    branches:
      - "main"

env:
  NODE_VERSION: "20.x"

jobs:
  get-protection-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Generator token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_RELEASE_APP_ID }}
          private_key: ${{ secrets.GH_RELEASE_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Get Branch Protection Rules
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ananda11k/test-update-branch-prot-rules/branches/main/protection
      - name: Update Branch Protection Rules
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ananda11k/test-update-branch-prot-rules/branches/main/protection \
            -f "required_status_checks[strict]=true" \
            -f "required_pull_request_reviews[required_approving_review_count]=true" \
            -f "enforce_admins=false" \
            -f "restrictions[apps[]]=a11k-org-bot" \
            -f "allow_force_pushes=true"
