name: Create Release

on:
  push:
    branches:
      - "main"

env:
  NODE_VERSION: "20.x"

jobs:
  protection-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Generator token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_RELEASE_APP_ID }}
          private_key: ${{ secrets.GH_RELEASE_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Get Branch Protection Rules
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ananda11k/test-update-branch-prot-rules/branches/main/protection
      - name: Update Branch Protection Rules
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ananda11k/test-update-branch-prot-rules/branches/main/protection \
            -d @override-branch-protection.json
      # - name: Update Branch Protection Rules
      #   env:
      #     GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      #   run: |
      #     curl -L \
      #       -X PUT \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer $GH_TOKEN" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/ananda11k/test-update-branch-prot-rules/branches/main/protection \
      #       -d '{"required_status_checks":{"strict":true,"contexts":[]},"enforce_admins":true,"required_pull_request_reviews":{"dismissal_restrictions":{"users":[],"teams":[]},"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":2,"require_last_push_approval":true,"bypass_pull_request_allowances":{"users":[],"teams":[]}},"restrictions":{"users":[],"teams":[],"apps":["a11k-org-bot"]},"required_linear_history":true,"allow_force_pushes":true,"allow_deletions":true,"block_creations":true,"required_conversation_resolution":true,"lock_branch":true,"allow_fork_syncing":true}'

      # - name: Update Branch Protection Rules
      #   env:
      #     GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      #   run: |
      #     gh api \
      #       --method PUT \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       /repos/ananda11k/test-update-branch-prot-rules/branches/main/protection \
      #       -f @override-branch-protection.json
